name: ai_mathnotes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  function_tree: ^0.9.1
  equations: ^5.0.2
  flutter_cube: ^0.1.1
  http: ^1.3.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  google_mlkit_text_recognition: ^0.15.0
  uuid: ^4.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.1
  image_gallery_saver: ^1.7.1
  image: ^4.1.3


  # ✅ FIXED: Use only the Git version of file_picker (no version number above it)
  file_picker: ^6.1.1


  docx_template: ^0.3.2
  archive: ^3.4.6
  xml: ^6.1.0

  # ✅ Compatible with xml ^5.3.1 and iOS builds
  flutter_math_fork: ^0.7.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 # ✅ updated to match Flutter 3.7.x compatibility

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    # - assets/avatar_default.png

  fonts:
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
